api.secret.key=pslhMdwb36TV7W7SibEa1ijEBfUxzjBm2obLvrfv
api.base.url=https://kassal.app/api/v1

endpoint.physical_stores=/physical-stores
endpoint.physical_stores_by_id= /physical-stores/{id}
endpoint.products=/products
endpoint.product_by_id=/products/id/{id}
endpoint.product_by_ean=/products/ean/{ean}
endpoint.product_by_url=products/find-by-url/single
endpoint.product_by_url_compare=products/find-by-url/compare

server.port=7001